# Site settings
title: |
  Open Knowledge International
  Annual Report
description: Looking back on 2017

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed

# Google Analytics (uncomment below to enable)
# analytics: UA-48180810-3
